### ISSUE TITLE
SoundCloud provider not working

### ISSUE THREAD

**Issue by juanbono** [r8/elixir-oembed#21]
Hi! First of all thank you for developing this library!

I'm trying to use it for SoundCloud tracks but every URL I tried results in `{:error, "oEmbed not found"}`. For example `OEmbed.for("https://soundcloud.com/forss/flickermood")`.

Do I need to do something in order to get it to work?

Thank you in advance :)

**Comment by r8** [comment]
Hi,

Thanks for the report!
No, you don't need to do anything, it's a library issue.
I was searching for `application/json+oembed` tag, but soundcloud is using `text/json+oembed`

Fixed in 25eed5d, I'll publish new minor version shortly

**Comment by juanbono** [comment]
Thank you! :D
