### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by APB9785** [r8/elixir-oembed#47]
Hi, thanks much for all the work on this OEmbed library.  Would it be possible to release the next version, so we can use the latest changes from `master`?  It would be a big help to resolve the warnings which are still present on v0.4.1.  Thanks!

**Comment by r8** [comment]
Hey @APB9785 
I was going to for a while now, I'll try to do it in the next few days

**Comment by r8** [comment]
@APB9785 Latest changes has been published to hex
